[project]
name = "pricediff"
version = "0.2.0"
description = "Price tracking dashboard"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "celery>=5.6.3",
    "python-dotenv>=1.0.0",
    "django>=6.0.5",
    "djangorestframework>=3.16.0",
    "djangorestframework-simplejwt>=5.5.0",
    "redis<8.0",
    "redislite>=6.2.912183",
    "scrapling[fetchers]>=0.4.8",
    "scrapling[fetchers]>=0.3.11",
    "pyvirtualdisplay>=3.0",
]

[tool.django]
settings = "pricediff.settings"
