# Generated by Django 6.0.5 on 2026-06-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='scrape_interval',
            field=models.IntegerField(default=24, help_text='Hours between automatic re-scrapes'),
        ),
    ]
