# Generated by Django 6.0.5 on 2026-06-11 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_last_scraped_at_product_scrape_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_scraped_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='scrape_interval',
        ),
    ]
