# Generated by Django 6.0.5 on 2026-06-11 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_product_last_scraped_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.product')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='app_scrapee_product_0270e1_idx')],
            },
        ),
    ]
